// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXhGYo6nQWXr6k-8xxcEQCyYQ1Xrz8BHU',
    appId: '1:537170760661:web:32c740b5f5ffd45fed235c',
    messagingSenderId: '537170760661',
    projectId: 'fir-01-ee78a',
    authDomain: 'fir-01-ee78a.firebaseapp.com',
    storageBucket: 'fir-01-ee78a.firebasestorage.app',
    measurementId: 'G-9RJFCJ8CWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5gld-JDS2EYoM1yJRjXVfh4lFa3RmsvA',
    appId: '1:537170760661:android:b54e4f6f462be9d8ed235c',
    messagingSenderId: '537170760661',
    projectId: 'fir-01-ee78a',
    storageBucket: 'fir-01-ee78a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvTDJAWb42M5YXh1DKLE4a5f8jzWSWG3I',
    appId: '1:537170760661:ios:02ff5e1043a7b1c5ed235c',
    messagingSenderId: '537170760661',
    projectId: 'fir-01-ee78a',
    storageBucket: 'fir-01-ee78a.firebasestorage.app',
    iosClientId: '537170760661-j99tustv62hpp6do8ie4696rmr1v5lm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvTDJAWb42M5YXh1DKLE4a5f8jzWSWG3I',
    appId: '1:537170760661:ios:02ff5e1043a7b1c5ed235c',
    messagingSenderId: '537170760661',
    projectId: 'fir-01-ee78a',
    storageBucket: 'fir-01-ee78a.firebasestorage.app',
    iosClientId: '537170760661-j99tustv62hpp6do8ie4696rmr1v5lm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXhGYo6nQWXr6k-8xxcEQCyYQ1Xrz8BHU',
    appId: '1:537170760661:web:000a47a81c39e0a6ed235c',
    messagingSenderId: '537170760661',
    projectId: 'fir-01-ee78a',
    authDomain: 'fir-01-ee78a.firebaseapp.com',
    storageBucket: 'fir-01-ee78a.firebasestorage.app',
    measurementId: 'G-J5JSR8R889',
  );
}
